### ISSUE TITLE
Array of enums

### ISSUE THREAD

**Issue by viktorgardart** [freshOS/Arrow#20]
Having trouble of parsing an array of enums. 

`var weekdays: [WeekDay]?`

**Response:**

``` json
{
  "weekdays": [1, 3]
}
```

**Parse:**

``` swift
self.weekdays <-- json["weekdays"]
```

Outcome is nil. :/

**Comment by s4cha** [comment]
Hi @viktorgardart,

Looks like forgot to support this case indeed, going to look into it and I'll ping you once it's live :)

**Comment by s4cha** [comment]
In the meantime this should do the trick  :)

``` swift

/// Parses Array of enums.
public func <-- <T: RawRepresentable>(inout left: [T], right: JSON?) {
    if let array = right?.data as? [Int] {
        left = array.map { $0 as? T.RawValue }.flatMap {$0}
            .map { T.init(rawValue: $0) }.flatMap {$0}
    }
}

```

**Comment by s4cha** [comment]
@viktorgardart this is now live in version 2.0.3 :)

Have a nice day,

**Comment by viktorgardart** [comment]
Working great when the enums are Ints. But when the type of the enum is String or what ever it does not work. 

I experimented a bit with this and did notice that `if let array =` were looking for a `Int` instead of `T.RawValue`

Fixed this with the pull request i've made.

**Comment by s4cha** [comment]
Good catch thanks for the PR! 🎉
