### ISSUE TITLE
Is the swift 3 branch stable? 

### ISSUE THREAD

**Issue by viktorgardart** [freshOS/Arrow#22]

**Comment by s4cha** [comment]
Hi @viktorgardart, yes we are going to merge it very soon. Have you tried it yet?

**Comment by viktorgardart** [comment]
Awesome, can try it now 👍

**Comment by s4cha** [comment]
Swift3 is now live on master version 3.0.0. We're having an issue with cocoa pods integration at the moment though. Carthage or manual install would be fine :)

**Comment by viktorgardart** [comment]
Just tried the swift3 branch and it works perfect 👌  🎉  

Awesome work 😄

**Comment by guillermo-carrasco** [comment]
That must be one of the fastest responses I've ever seen on a public repo, great work @s4cha ! 🎉

**Comment by s4cha** [comment]
Haha thanks @guillermo-carrasco , the cocoaPods integration for swift 3 is still broken though :/
