### ISSUE TITLE
Release 3.0.3 not available on master

### ISSUE THREAD

**Issue by maxkonovalov** [freshOS/Arrow#29]
The latest tag `3.0.3` is missing from `master` branch and also from CocoaPods specs repo, it shows v.3.0.2 only. Because of this the **ws** pod fails to install:
>[!] Unable to find a specification for `Arrow3.0.3` depended upon by `ws`

**Comment by s4cha** [comment]
@maxkonovalov Indeed the code wasn't pushed :/ my bad:) This is now on Cocoapods as well
Let me know if this is fixed on your end.
Thanks,
