### ISSUE TITLE
Get notified if a key is missing

### ISSUE THREAD

**Issue by s4cha** [freshOS/Arrow#31]
Find a way to get notified if a parsing error occurs, for example a missing key

**Comment by maxkonovalov** [comment]
@s4cha how about making the `deserialize` func throwing?

**Comment by s4cha** [comment]
@maxkonovalov , good question :)

Arrow didn't have error handling (on purpose) but this is something we can discuss. Having given this some time I think it might not be worth it. I personally never had the need to test errors in JSON parsing as I believe that this is an Api-side problem. 

On the iOS side, Unit tests test against local JSON files to make sure parsing works as expected.
On the backed side, unit tests test that the api sends the correct JSON structures.

Could you elaborate on a concrete case where we need to catch parsing errors?

**Comment by maxkonovalov** [comment]
@s4cha agreed, I don't have such use cases either. For me it works perfect just to do nothing if the key is not there or could not be parsed. Other frameworks usually provide a way to specify a fallback value for that case.
