### ISSUE TITLE
please make dateFormatter in Arrow.swift public

### ISSUE THREAD

**Issue by glaurent** [freshOS/Arrow#32]
I need to parse dates which are not in the current time zone, so I need to set the timezone on Arrow's dateFormatter, but as it is I can't.

**Comment by s4cha** [comment]
Hi @glaurent, 
Thanks for pointing this out ! This is a welcome addition indeed, will ping you when it's live:)

**Comment by s4cha** [comment]
Ok so there will be two ways to set this

Globally
 ```swift
let df = DateFormatter()
df.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
df.timeZone = TimeZone(secondsFromGMT: 60*60*5)

Arrow.setDateFormatter(df)
```

On a per key basis
 ```swift
aDate <-- json["created_at"]?.dateFormatter(df)
```

**Comment by s4cha** [comment]
https://github.com/freshOS/Arrow/releases/tag/3.0.4 :)

**Comment by glaurent** [comment]
This is perfect, thank you very much 😊👍
