### ISSUE TITLE
How do I instantiate a model directly from a string containing json?

### ISSUE THREAD

**Issue by ntkon** [freshOS/Arrow#40]
Hi, sorry to ask such a dumb question, but I can't figure out how to do a simple decode from a string containing my json to my model object:
```
struct doh: Codable {
  var homer = ""
}
extension doh : ArrowParsable {
  public mutating func deserialize(_ json: JSON) {
    homer <-- json["homer"]
  }
}

```
now to create one:

```
let myJson = "{ \"homer\": \"simpson\"}"
var aSimpson = doh()
aSimpson.deserialize(JSON(myJson)!)
```
this doesn't work! How do I create a `doh` object from the `myJson` string?

Thanks.

**Comment by s4cha** [comment]
Hi @ntkon,

You need to go through native `JSONSerialization` in order for it to work.
(Actually this could be a great future improvement to support JSON strings)

Here is the working version:
```swift
let myJson = "{ \"homer\": \"simpson\"}"

guard let jsonData = myJson.data(using: .utf8),
    let jsonObject = try? JSONSerialization.jsonObject(with: jsonData, options: .mutableContainers),// as? NSDictionary,
    let json = JSON(jsonObject) else {
    return
}

var aSimpson = doh()
aSimpson.deserialize(json)
print(aSimpson)
```

Also the `aSimpson.deserialize(json)` part can be written like:
```swift
aSimpson <-- json
```

Hope this helps :)

**Comment by ntkon** [comment]
Thanks @s4cha, much appreciated. I'm liking using arrow, ws and stevia - nice tools.

**Comment by s4cha** [comment]
@ntkon can we close this ?

**Comment by ntkon** [comment]
Sorry, I forgot to do that. Closed :)
