### ISSUE TITLE
How do you use Arrow with Moya+RxSwift

### ISSUE THREAD

**Issue by zkon** [freshOS/Arrow#41]
I'm using Moya + RxSwift and would like to use Arrow to do the parsing. Has anyone ever tried this? 

Thanks.

**Comment by s4cha** [comment]
@zkon I've never used Moya but I'm going to try it this afternoon and will report back :)

**Comment by s4cha** [comment]
@zkon Ok I've been checking out the Moya repo and here is how I plugged Arrow based on their example project.

Create a strongly typed `Repository`
```swift
struct Repository {
    var name = ""
}
```
Add JSON Mapping
```swift
extension Repository: ArrowParsable {
    mutating func deserialize(_ json: JSON) {
        name <-- json["name"]
    }
}
```

In the `downloadRepositories` function, use this code instead
```swift
let response = try result.dematerialize()
let value = try response.mapJSON()
let json = JSON(value)
let repositories = json?.collection?.map { json -> Repository in
    var repo = Repository()
    repo.deserialize(json)
    return repo
}
self.repos = repositories ?? [Repository]()
self.tableView.reloadData()
```

Hope this helps :)

PS: If you use Arrow and Alamofire, then you might like [ws](https://github.com/freshOS/ws)

**Comment by s4cha** [comment]
@zkon Have you had the chance to try it?

**Comment by zkon** [comment]
Hi @s4cha, sorry for the late response. Unfortunately I was outvoted on using Arrow for the project I was hoping for. Your suggestion looks reasonable and when I get a chance I'll use it.

I've actually used ws in another project and liked it. I've been using Moya now for a while and have found it pretty good also, especially if you are using rx.

Thanks for your assistance, I'll close the issue.

**Comment by s4cha** [comment]
Hey @zkon Thanks for your answer 👍
