### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by DmitryShapovalov** [freshOS/Arrow#48]
Hello,

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs etc will need to provide a privacy manifest.
Does UIView-Shimmer need to include this manifest?

Here are some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
https://developer.apple.com/videos/play/wwdc2023/10060/

Thanks

**Comment by s4cha** [comment]
Hey @DmitryShapovalov, same here, I'm going to takle it this week. Thanks a ton for your patience and thank you for the links 💯

**Comment by DmitryShapovalov** [comment]
Cool, thank you!

**Comment by s4cha** [comment]
Latest release [6.0.1](https://github.com/freshOS/Arrow/releases/tag/6.0.1) has PrivacyInfo.xcprivacy. Let me know if that looks good to you :)
